### ISSUE TITLE
`Reading from "node:path" is not handled by plugins` since 3.0.0-beta.12

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud-libraries/nextcloud-files#714]
```js
ERROR in node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /home/admin/Docker/server/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/home/admin/Docker/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/admin/Docker/server/node_modules/tapable/lib/Hook.js:18:14)
    at Object.processResource (/home/admin/Docker/server/node_modules/webpack/lib/NormalModule.js:835:8)
    at processResource (/home/admin/Docker/server/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/home/admin/Docker/server/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/home/admin/Docker/server/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/home/admin/Docker/server/node_modules/webpack/lib/NormalModule.js:825:3)
    at NormalModule.build (/home/admin/Docker/server/node_modules/webpack/lib/NormalModule.js:969:15)
    at /home/admin/Docker/server/node_modules/webpack/lib/Compilation.js:1377:12
    at NormalModule.needBuild (/home/admin/Docker/server/node_modules/webpack/lib/NormalModule.js:1257:32)
    at Compilation._buildModule (/home/admin/Docker/server/node_modules/webpack/lib/Compilation.js:1358:10)
    at /home/admin/Docker/server/node_modules/webpack/lib/util/AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (/home/admin/Docker/server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/home/admin/Docker/server/node_modules/webpack/lib/util/AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (/home/admin/Docker/server/node_modules/webpack/lib/util/AsyncQueue.js:282:12)
    at process.processImmediate (node:internal/timers:478:21)
 @ ./node_modules/@nextcloud/files/dist/index.mjs 4:0-81 260:27-28 277:11-12 280:11-12 285:13-14 288:11-12 315:96-97 333:14-15
 @ ./apps/files/src/views/favorites.ts 8:0-44 52:22-37 69:22-37
 @ ./apps/files/src/main.ts 18:0-54 70:0-21
```

cc @susnux 
Regression from beta11. I'm guessing this is the new jest magic :)

**Comment by susnux** [comment]
Well there are two issues here:
1. Why can webpack not resolve node protocol, weird.
   * Answer: https://github.com/webpack/webpack/issues/14166 and https://github.com/Richienb/node-polyfill-webpack-plugin/issues/19 
3. Why is the `node:` protocol introduced in the first place? We simply import from `path` and not `node:path` somehow the Typescript import is transformed to a `node:` protocol import.
  * Answer: `rollup-plugin-node-externals` defaults to add that protocol prefix, which is basically a good idea to prevent issues with same named 3rdparty modules, but as in 1: Webpack can not handle it...

Two solutions here:
1. Simply polyfill `node:` core modules on the dist files? But normally I would say it the task of the library user.
2. Configure the plugin to strip of that prefix rather than adding it.

I would vote for 2, @skjnldsv ?

**Comment by skjnldsv** [comment]
> I would vote for 2, @skjnldsv ?

seconded

**Comment by juliushaertl** [comment]
This should already be fixed in the last release, right? I'm not sure if the fix works as intended. Just because when updating `@nextcloud/files` in [text](https://github.com/nextcloud/text/commit/6935fa6ea79d41ce60bc7efbeafd491e91b9f0a8), the build passes without error (I could see the above error with beta.12) but the bundled code does not do anythng, no error, no warning.

Is it a requirement with https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/10 to polyfill path and buffer which seemed to be the ones causing issues myself in the app?


Ref https://github.com/nextcloud-libraries/webpack-vue-config/issues/450 for buffer,

**Comment by susnux** [comment]
> Is it a requirement with https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/10 to polyfill path and buffer which seemed to be the ones causing issues myself in the app?

Currently the library does not polyfill anything, which I think is the correct way to do for a library.
The library user has to make sure that its target supports all modules, e.g. if you target a browser you probably want to polyfill `path` as that is not available, as written in the linked issue the `Buffer` module is not compatible with browsers so event that one needs to be polyfilled.
